from django.urls import path
from .views import *

urlpatterns = [
    path('app_home/', app_home, name='app_home'),
    path('show_resume/<int:pk>/', show_resume, name='show_resume'),
    path('create_resume/', create_resume, name='create_resume'),
    path('add_education/<int:pk>/', add_education, name='add_education'),
    path('add_experience/<int:pk>/', add_experience, name='add_experience'),
    path('add_skill/<int:pk>/', add_skill, name='add_skill'),
    path('add_language/<int:pk>/', add_language, name='add_language'),
    path('add_summary/<int:pk>/', add_summary, name='add_summary'),
    path('update_education/<int:pk>/', update_education, name='update_education'),
    path('update_experience/<int:pk>/', update_experience, name='update_experience'),
    path('update_skill/<int:pk>/', update_skill, name='update_skill'),
    path('update_language/<int:pk>/', update_language, name='update_language'),
    path('update_info/<int:pk>/', update_info, name='update_info'),
    path('update_summary/<int:pk>/', update_summary, name='update_summary'),
    path('download_template/<int:pk>/', download_template, name='download_template'),
    path('resume/<int:pk>/download/', ResumePDFView.as_view(), name='download_resume'),
    path('delete_education/<int:pk>/', delete_education, name='delete_education'),
    path('delete_experience/<int:pk>/', delete_experience, name='delete_experience'),
    path('delete_skill/<int:pk>/', delete_skill, name='delete_skill'),
    path('delete_language/<int:pk>/', delete_language, name='delete_language'),
    path('add_other_sec/<int:pk>/', add_other_sec, name='add_other_sec'),
    path('add_other_sec_item/<int:pk>/', add_other_sec_item, name='add_other_sec_item'),
    path('add_other_short/<int:pk>/', add_other_short, name='add_other_short'),
    path('add_other_short_item/<int:pk>/', add_other_short_item, name='add_other_short_item'),
    path('delete_sec/<int:pk>/', delete_sec, name='delete_sec'),
    path('delete_item/<int:pk>/', delete_item, name='delete_item'),
    path('delete_short_sec/<int:pk>/', delete_short_sec, name='delete_short_sec'),
    path('delete_item_short/<int:pk>/', delete_item_short, name='delete_item_short'),
    path('delete_resume/<int:pk>/', delete_resume, name='delete_resume'),
]