# Generated by Django 6.0.4 on 2026-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeheaders',
            name='resume_picture_link',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='resumes',
            name='unique_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
