# Generated by Django 6.0.4 on 2026-04-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_resumes_resumelanguages_resumeheaders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeheaders',
            name='resume_picture',
            field=models.ImageField(blank=True, null=True, upload_to='resume_pictures/'),
        ),
    ]
