# Generated by Django 6.0.4 on 2026-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_resumeheaders_resume_picture_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeeducations',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resumeeducations',
            name='start_date',
        ),
        migrations.AddField(
            model_name='resumeeducations',
            name='passing_year',
            field=models.CharField(default='2010', max_length=20),
        ),
    ]
