# Generated by Django 6.0.4 on 2026-04-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_resumeheaders_resume_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeheaders',
            old_name='Resume',
            new_name='resume',
        ),
    ]
