# Generated by Django 6.0.4 on 2026-05-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_alter_resumes_user_alter_resumesummaries_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeOtherSecShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heeder', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOtherSecShortItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('other_sec_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.resumeothersecshort')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOtherSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOtherSectionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('other_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.resumeothersections')),
            ],
        ),
    ]
