# Generated by Django 6.0.4 on 2026-05-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_resumeothersecshort_resumeothersecshortitems_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeOtherSecShort',
            new_name='ResumeOtherSecShorts',
        ),
        migrations.RenameField(
            model_name='resumeothersecshorts',
            old_name='heeder',
            new_name='header',
        ),
    ]
