# Generated by Django 6.0.4 on 2026-05-05 03:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0010_alter_resumeheaders_resume_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeheaders',
            name='resume_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
