# Generated by Django 6.0.4 on 2026-05-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0011_alter_resumeheaders_resume_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeheaders',
            name='resume_picture',
            field=models.ImageField(blank=True, null=True, upload_to='resume_pictures/'),
        ),
    ]
